---
fusion_callers:
  type: 'List'
  required: true
  help: 'List of fusion callers for calling'
  default:
    - arriba
    - star-fusion
    - fusioncatcher
  choices:
    - arriba
    - star-fusion
    - fusioncatcher
reference_genome_version:
  type: 'String'
  required: true
  help: 'Version of reference genome for processing'
  default: 'GRCh38'
  choices:
    - hg19
    - GRCh37
    - hg38
    - GRCh38
    - mm10
    - GRCm38
fusioncatcher_reference_dir:
  type: 'Path'
  mode: 'r'
  required: false
  help: 'Absolute path to reference directory for fusioncatcher'
starfusion_reference_dir:
  type: 'Path'
  mode: 'r'
  required: false
  help: 'Absolute path to reference directory for starfusion'
arriba_star_index_dir:
  type: 'Path'
  mode: 'r'
  required: false
  help: 'Absolute path to index directory for arriba'
arriba_assembly_fasta:
  type: 'Path'
  mode: 'r'
  required: false
  help: 'Absolute path to assembly fasta for arriba'
arriba_annotation_gtf:
  type: 'Path'
  mode: 'r'
  required: false
  help: 'Absolute path to annotation GTF for arriba'
output_dir:
  type: 'Path'
  mode: 'w'
  required: true
  help: 'Absolute path to output directory'
sample_id:
  type: 'String'
  required: true
  help: 'Sample identifier'
paired_end:
  type: 'Bool'
  required: true
  help: 'Indicator of whether sample is paired end or not'
  default: 'true'
input:
  type: 'InputNamespace' # Custom type
  required: true
  help: 'Input samples'
  elements:
    FASTQ:
      type: 'ListFASTQPairs' # Custom type
      required: true
      help: 'Input FASTQs'
      elements:
        R1:
          type: 'Path'
          mode: 'r'
          required: true
          help: 'Absolute path to R1 FASTQ'
        R2:
          type: 'Path'
          mode: 'r'
          required: false
          help: 'Absolute path to R2 FASTQ'
